# tell travis that we are using docker
sudo: required
services:
  - docker

# build image of Dockerfile.dev
before_install:
  - docker build -t rogerwschmidt/docker-react-example -f Dockerfile.dev .

# run test suite
script:
  - docker run -e CI=true rogerwschmidt/docker-react-example npm run test

# Tell travis how to deploy to AWS
deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: docker-react
  env: DockerReact-env
  bucket_name: elasticbeanstalk-us-east-1-509436554991
  bucket_path: docker-react # same as app name
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"