version: '3'

services: 
  web:
    build:
      # where to look for files to build
      context: . 
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app